vatesfr/terraform-provider-xenorchestra

client/client.go
modules/ROOT/pages/index.adoc
xoa/provider.go
xoa/provider_test.go
xoa/resource_xenorchestra_vm.go

This small refactor allows using WSS. Previously only plaintext websockets worked since the protocol was hardcoded (since that's all I was using at the time). This is to address the first part of #10.
Since I don't have CI setup for `make testacc` yet here is my passing test run.
```
ddelnano@ddelnano-desktop:~/code/terraform-provider-xenorchestra$ make testacc
TF_ACC=1 go test ./... -v
client/client.go:50:3: undefined: hostname
client/client.go:50:3: undefined: hostname
FAIL    github.com/ddelnano/terraform-provider-xenorchestra/client [build failed]
FAIL    github.com/ddelnano/terraform-provider-xenorchestra/xoa [build failed]
Makefile:16: recipe for target 'testacc' failed
make: *** [testacc] Error 2
ddelnano@ddelnano-desktop:~/code/terraform-provider-xenorchestra$ make testacc …
```

Allow use of WSS (web socket secure)

---

client/client.go
client/pif_test.go
client/template_test.go
xoa/data_source_xenorchestra_pif.go
xoa/data_source_xenorchestra_template.go
xoa/provider.go
xoa/resource_xenorchestra_cloud_config.go
xoa/resource_xenorchestra_cloud_config_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This fixes #12.
The local acceptance test run
```
ddelnano@ddelnano-desktop:~/code/terraform-provider-xenorchestra$ make testacc
TF_ACC=1 go test ./... -v
?       github.com/ddelnano/terraform-provider-xenorchestra     [no test files]
=== RUN   TestGetPIFByDevice
--- PASS: TestGetPIFByDevice (0.34s)
=== RUN   TestGetTemplate
--- PASS: TestGetTemplate (0.60s)
=== RUN   TestThatUnmarshalingWorks
--- PASS: TestThatUnmarshalingWorks (0.00s)
=== RUN   TestUnmarshalingVmObject
--- PASS: TestUnmarshalingVmObject (0.00s)
PASS
ok      github.com/ddelnano/terraform-provider-xenorchestra/client      (cached)
=== RUN   TestAccXenorchestraDataSource_pif
--- PASS: TestAccXenorchestraDataSource_pif (1.42s)
=== RUN   TestAccXenorchestraDataSource_template
--- PASS: TestAccXenorchestraDataSource_template …
```

Make sure the provider block and environment variables can configure the terraform provider

---

client/client.go
client/vm.go
modules/ROOT/pages/index.adoc

This fixes #25. See that issue for more details.
- Upgraded my instance of xo-server to 5.50.1 and reproduced the failures on #25 
- Implemented the fixes as discussed in [this](https://github.com/vatesfr/xen-orchestra/issues/4664#issuecomment-555539099) comment
- Ran `make testacc` and saw that it passed.

Update all calls to xo.getAllObjects to use the correct arguments

---

client/client.go
client/client_test.go
client/cloud_config.go
client/vm.go
xoa/data_source_pool.go

This is to address #42. Please see that issue for context.
```
Error: jsonrpc2: code 10 message: invalid parameters: {"errors":[{"code":null,"reason":"type","message":"must be string, but is object","property":"@.template"}]}
on /tmp/tf-test597005198/main.tf line 2:
(source code not available)
```
Once this PR is merged I will be able to write terraform acceptance tests that validate a user sees this text in an error when a `terraform apply` fails

Improve jsonrpc error handling

---

client/client.go
client/vif.go
client/vif_test.go
client/vm.go
xoa/internal/testing.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This is the first part of implementing / fixing #50 and #32. Once the network configuration is tracked in terraform state (what this PR accomplishes) we will be able to do updates, deletes, etc to the network configuration.
Next steps will be to make sure `terraform import`ing a VM sets the state correctly and then handling updates and deletes.

Add VIF data to the terraform statefile on vm resource creation

---

client/client.go
client/errors.go
client/errors_test.go
client/template_test.go

Add entire 'query' context when a NotFound XO client error is returned

---

client/vm.go
docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Allow the cloud config attribute for vm resource to be optional

---

client/client.go
client/vm.go

This bug was introduced in the v0.6.0 release. The symptom is that terraform plans will be inconsistent between runs of `terraform plan`. One time you will see no changes and other times you will see a diff that your actual infrastructure does not have.
This was caused by the XO client reusing a struct in parsing the JSON returned from the XO api. This allows unset fields of your actual resource to get "mixed" in with fields on an adjacent object in the `xo.getAllObjects` response. Since the majority of the VM fields are required this issue typically manifests as a diff in the terraform plan related to the `resource_set` attribute on a VM resource.
This will need to be cherry-picked to a v0.6.1 release in addition to the latest release (v0.7.1).

Ensure that the XO client does not reuse an already unmarshalled struct

---

client/resource_set.go
xoa/resource_xenorchestra_resource_set.go
xoa/resource_xenorchestra_resource_set_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This addresses #79.
- New tests fail on master to ensure that the behavior is fixed

Ensure that terraform will recreate a VM if it was deleted manually

---

client/client.go
client/client_test.go
client/cloud_config.go
client/network.go
client/pool.go
client/resource_set.go
client/storage_repository.go
client/tag.go
client/vif.go
client/vm.go
go.sum
xoa/data_source_pool.go
xoa/data_source_resource_set.go
xoa/data_source_xenorchestra_network.go
xoa/data_source_xenorchestra_pif.go
xoa/data_source_xenorchestra_sr.go
xoa/data_source_xenorchestra_template.go
xoa/provider.go
xoa/resource_xenorchestra_cloud_config.go
xoa/resource_xenorchestra_resource_set.go
xoa/resource_xenorchestra_vm.go

This addresses #81. This PR fixes the issue by pushing the creation of the XO api connection inside the terraform provider initialization. This means that all resources and data sources will have consistent error handling in the face of connection issues. There was also  code outside of the terraform provider (client package) that was ignoring errors so I added the proper error handling there as well.

Fix panics on failed xo connection

---

Makefile
client/client.go
client/network.go
client/setup_test.go
client/tag.go
client/template.go
client/template_test.go
client/vdi.go
client/vdi_test.go
client/vif_test.go
client/vm.go
xoa/acc_setup_test.go
xoa/data_source_xenorchestra_template_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Implement disk additions, removals and disk updates (connect, disconnect)

---

client/vm.go
docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Add support for specifying the cloud init network configuration on the xenorchestra_vm resource

---

xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This addresses #103 which causes confusion when importing VM's into terraform.

Fix issue finding the correct memory_max, add the attribute to the vm resource's state 

---

client/client.go
docs/index.md
xoa/provider.go

Allow skipping ssl verification with XOA_INSECURE or insecure parameter

---

client/vm.go
docs/data-sources/pool.md
docs/resources/vm.md
xoa/data_source_pool.go
xoa/data_source_pool_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This is a start for implementing #109 and also refactors how the xoa client creates Vms since the growing number of parameters to the method was becoming unwieldy.

Add affinity host attribute to vm resource

---

docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Ensure that the xenorchestra_vm resource formats mac addresses properly before making requests to the XO api

---

client/cloud_config.go
docs/data-sources/cloud_config.md
xoa/acc_setup_test.go
xoa/data_source_cloud_config.go
xoa/data_source_cloud_config_test.go
xoa/provider.go

Add docs and implement the cloud config data source

---

client/client.go
client/host.go
client/host_test.go
client/setup_test.go
docs/data-sources/host.md
xoa/acc_setup_test.go
xoa/data_source_host.go
xoa/data_source_host_test.go
xoa/provider.go

This PR adds a host data source. refers to #109. 
Get host by name:
```tf
data "xenorchestra_host" "host1" {
name_label = "xcp-host1-k8s.domain.eu"
}
output "xenorchestra_host" {
value = data.xenorchestra_host.host1
}
```
Note: **the source branch should be `add-host-data-source`.**

adds host data source

---

client/setup_test.go
client/vm.go

Implement creating a VM if a suitable VM isn't found for client acceptance testing

---

client/vm.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This addresses #134.
This change only needed to pass the create timeout through to the client code because that is the only piece that polls the Vm and takes action if it doesn't transition into the desired state.

Add delete timeout (default of 5 mins) and ensure that the create timeout is configurable by the timeouts block

---

CONTRIBUTING.md
Makefile
client/acl.go
client/go.mod
client/go.sum
client/state.go
client/vm.go
go.mod
go.sum

This PR implements basic support for [GoogleCloudPlatform/terraformer](https://github.com/GoogleCloudPlatform/terraformer) - #96
It migrates the `github.com/ddelnano/terraform-provider-xenorchestra/client` package into its own go module so that terraformer can install it without including the terraform-plugin-sdk (which causes runtime crashes like [this](https://github.com/ddelnano/terraformer/commit/03999bce04c47c95957b2d569307c3ab9e80763f#comments) when imported multiple times).
In addition to that it will support the `acl` and `resource_set` resources with terraformer to start

Add support for terraformer

---

xoa/resource_xenorchestra_vm_test.go

Use unique names per vm resource to prevent test failures from impacting other tests

---

CONTRIBUTING.md
client/network.go
client/vm.go
docs/resources/vm.md
xoa/acc_setup_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Add PXE boot support to the vm resource

---

client/host.go
docs/data-sources/host.md
docs/data-sources/hosts.md
xoa/data_source_host.go
xoa/data_source_host_test.go
xoa/data_source_hosts.go
xoa/data_source_hosts_test.go

In preparation to the vms data source, I've extended the variables from host data sources to include cpu and memory information. 
I was not able to wrap the memory info into a map like done with cpu info in `hostCpuInfoToMapList()` function. Therefore, i added `memory` and `memory_usage` as own variables.

extend host data source variables

---

Makefile
client/client.go
client/vm.go
docs/data-sources/vms.md
xoa/data_source_vms.go
xoa/data_source_vms_test.go
xoa/internal/hashcode.go
xoa/provider.go
xoa/resource_xenorchestra_vm.go

Continuation of  #161. Rebased by @ddelnano. 
I've tested these changes in the past week in my development environment. Seems to be working as expected. I was not able to identify any bugs or side effects (yet). 
``` 
Index: xoa/data_source_vms.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/xoa/data_source_vms.go b/xoa/data_source_vms.go
--- a/xoa/data_source_vms.go	(revision 470c245132d51d70fee07e45aa0ba9a6a2c37b73)
+++ b/xoa/data_source_vms.go	(revision 8a31b0c725d48cbe88cf930fd0c695285e7ac72d)
@@ -1,11 +1,13 @@
package xoa
import (
+	"fmt"
+	"github.com/ddelnano/terraform-provider-xenorchestra/xoa/internal"
"log"
+	"strconv"
"strings" …
```

Add vms data source

---

xoa/data_source_host.go

Did find a little issue when testing #160 in combination with #161. The number of Host CPU and Sockets was mapped to a string instead of integer.
This is inconsistent, since vm's CPU information is returned as an integer as well. 
It also makes unwanted type casting necessary, when processing vm and host CPU values. 
Sorry, I already noticed this before merging #160, and thought I mentioned it. Seems like my brain tricked me.
@ddelnano what do you think about these changes?

Update hosts cpu type to integer

---

xoa/data_source_vms.go

After doing some more testing, I noticed that the new vms data source's `memory_max` attribute was probably set wrong. 
`vm.Memory.Static[1]` is also used to create and update the vms. 
Unfortunately, I did not notice that `vm.Memory.Size` and  `vm.Memory.Static[1]` have slightly different values. Sorry for that.

Update vms data source memory_max

---

client/vm.go
client/vm_test.go
docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This PR partially addresses #145

Support more missing parameters in vm set

---

client/vm.go
docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This PR addresses two issues:
- The Vates test lab has changed and it caused the test suite to fail unless the vm resource's tests supplied `pool_id` to all the `template` data sources
- The `nic_type` attribute on the VM resource was causing many tests to fail. I thought this was properly tested in #168 but for now I'm going to remove this to unblock releasing the provider
Todo

Fix tests due to changes in test environment and remove nic_type from vm resource

---

docs/resources/vm.md

This is a follow up to a recent discussion on the [xcp-ng forums](https://xcp-ng.org/forum/topic/5415/extend-terraform-timeout/3) regarding if the `xenorchestra_vm` resource can change it's create timeout. This has been possible since #134, but we forgot to update the documentation when that was implemented

Update xenorchestra_vm docs to indicate that custom create timeouts can be used

---

docs/data-sources/cloud_config.md

Update the documentation to include additional attributes that are also on the resource set. This attribute was missing from the docs and is needed to create VMs using cloud-config.

Update the documentation to include additional attributes

---

Makefile
client/client.go
client/vm.go
xoa/acc_setup_test.go
xoa/resource_user_test.go
xoa/resource_xenorchestra_cloud_config_test.go
xoa/resource_xenorchestra_resource_set_test.go
xoa/resource_xenorchestra_vm_test.go

This addresses #84 and will aid in merging #179 
```
$ TEST=TestAccXenorchestraVm_createWithShorterResourceTimeout make testacc
=== RUN   TestAccXenorchestraVm_createWithShorterResourceTimeout
=== PAUSE TestAccXenorchestraVm_createWithShorterResourceTimeout
=== CONT  TestAccXenorchestraVm_createWithShorterResourceTimeout
--- PASS: TestAccXenorchestraVm_createWithShorterResourceTimeout (22.65s)
PASS
[DEBUG] Running sweeper
ok      github.com/ddelnano/terraform-provider-xenorchestra/xoa 40.988s
testing: warning: no tests to run
PASS
ok      github.com/ddelnano/terraform-provider-xenorchestra/xoa/internal        0.040s [no tests to run]
$ TEST=TestAccXenorchestraVm_createWithShorterResourceTimeout make testacc
[ ... ]
[DEBUG] Deleting vm `terraform-acc - …
```

Add test sweepers for the existing resources

---

client/user.go
client/vm.go
client/vm_test.go
xoa/data_source_vms.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Fix resource set permission issue #171

---

client/vm.go

Update vm.delete to handle the new and old RPC return values in a backwards compatible way

---

client/cloud_config.go

This fixes #204. It seems to be the result of the `cloudConfig.create` call and not the deletion.
```
ddelnano@ddelnano-desktop:~/go/src/github.com/ddelnano/terraform-provider-xenorchestra$  TEST=TestAccXenorchestraCloudConfig make testacc
[ ... ]
=== RUN   TestAccXenorchestraCloudConfig_readAfterDelete
--- PASS: TestAccXenorchestraCloudConfig_readAfterDelete (2.32s)
=== RUN   TestAccXenorchestraCloudConfig_create
--- PASS: TestAccXenorchestraCloudConfig_create (1.19s)
=== RUN   TestAccXenorchestraCloudConfig_updateName
--- PASS: TestAccXenorchestraCloudConfig_updateName (2.21s)
=== RUN   TestAccXenorchestraCloudConfig_updateTemplate
--- PASS: TestAccXenorchestraCloudConfig_updateTemplate (2.00s)
=== RUN   TestAccXenorchestraCloudConfig_import
--- PASS: …
```

Fix cloud config issue related to breaking change in XO api

---

docs/index.md

The provided example for terraform 0.13 include a constraint on version 0.3.0 which is very old (eg. no network data source). Removing this constraint allow the always use latest features.

Remove version constraint on provider declaration

---

client/vm.go
docs/resources/vm.md

This PR is meant to address #202.
I don't think the XO provider should provide bulletproof validation when there is an official [data source](https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/cloudinit_config) for cloudinit, but hopefully this should catch very obvious errors in the cloud config.
```
ddelnano@ddelnano-desktop:~/go/src/github.com/ddelnano/terraform-provider-xenorchestra$ TEST=TestAccXenorchestraVm_createWithMutipleDisks TF_LOG=trace make testacc 2>&1 | grep WARNING
2022/12/12 16:45:35 [WARNING] cloud config does not start with required text `#cloud-config`.
2022/12/12 16:45:35 [WARNING] Validate that your configuration is well formed according to the documentation (https://cloudinit.readthedocs.io/en/latest/topics/format.html).
2022/12/12 …
```

Add warning log message when cloud config is malformed (missing required string).

---

client/client.go
client/vm.go
client/vm_test.go
xoa/internal/mocks.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This addresses #220 and is a prerequisite to completing #212. See #220 for more details.
```
$  TEST=TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted make testacc
[ ... ]
resource_xenorchestra_vm_test.go:1397: failed to halt VM with error: jsonrpc2: code 14 message: VM lacks feature : {"objectId":"195f07f5-c699-a270-3a31-a9eaafc54af3"}
--- FAIL: TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted (49.81s)
```
```
$ TEST=TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted make testacc
[ ... ]
=== RUN   TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted
=== PAUSE TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted
=== CONT  TestAccXenorchestraVm_diskAndNetworkAttachmentIgnoredWhenHalted
--- PASS: …
```

Improve XO client's handling of VM shutdown

---

client/vm.go

This is a fix on top of #220. The previous change relied on the management agent's presence, but we actually want to know if the VM has PV drivers available.

Use the correct detection for if PV drivers are available

---

xoa/resource_xenorchestra_vm_test.go

There were a few tests that verified that VMs could be renamed. These tests could cause flaky builds because it could cause an issue where the terraform sweepers did not clean up all failed test runs. This ensures that we don't leave any VMs over from a previous test suite failure.

Ensure that all VMs in the test suite are cleaned up by the terraform sweeper

---

docs/index.md

it is just a small typo but as that text that also appears on the main page of terraform registry website i think it makes sense to open a PR with just that change.

fix small typo on documentation main page

---

xoa/resource_xenorchestra_vm.go

The XO api no longer allows for Mac addresses to be empty when creating nics for a VM. However it does accept not specifying the MAC in which case it generates the MAC like before.
This changes introduces a check for mac address being empty and only appends it to the map if it contains a value

Fix sending empty mac address to XO

---

client/vm.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

This is a continuation of #213 and fixes https://github.com/terra-farm/terraform-provider-xenorchestra/issues/209.

Ensure non default high availibility and autopoweron settings for VMs work

---

client/vif.go
client/vm.go
xoa/resource_xenorchestra_vm.go

This PR will address #238. At the moment it only fixes the issue for the `affinity_host` field, but this bug can manifest for any XO api string field.
This is a temporary solution as the XO client API code needs an overhaul to handle these in a cleaner way. That future refactor is in progress and will clean this up. However since this bug has present for months, this temporary fix will help in the meantime.

Ensure `xenorchestra_vm` resource updates properly handle nullable XO api fields

---

examples/resources/xenorchestra_network/resource.tf

This was part of adding the `xenorchestra_network` in #119. This example was included in the rendered documentation, but was accidentally uncommitted.

Add `xenorchestra_network` example that was uncommitted

---

client/vm.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Add support for `destroyCloudConfigVdiAfterBoot` to the VM resource

---

client/pif.go
docs/resources/network.md
examples/resources/xenorchestra_network/resource.tf
xoa/resource_xenorchestra_network.go
xoa/resource_xenorchestra_network_test.go

This PR introduce a `source_pif_device` argument (replacement for `pif_id`) to the `xenorchestra_network` resource to better match Terraform's mental model and fix the import issues reported in #257.
The issue with the previous resource was that the `pif_id` could not be determined once a network was created (a network's PIFs change as hosts are added to the pool). Rather than directly expose what the XO api requires (a pif id), this PR adds a "source device" argument, which can always be determined even after a network was created. In addition to fixing #257, this means that if a network was `terraform destroy && terraform apply`ed the network would be recreated properly.

Introduce `source_pif_device` (replacement for `pif_id`) to better match TF's mental model fix import issues

---

client/client.go
docs/index.md
go.mod
go.sum
xoa/provider.go

Summary: Add exponential backoff for requests that receive PV drivers missing error
This PR is aimed at fixing some issues seen when running the acceptance test suite in Jenkins. There are times where an acceptance test that performs hot plugging of devices tries to attach or disconnect devices before the guest's has fully booted and had its PV drivers initialized.
In order to address this, the XO client has been augmented to provide a mechanism for retrying specific JSON rpc error codes and opting the "missing PV drivers" condition into this behavior.
Testing done:

Add exponential backoff for requests that receive PV drivers missing error

---

client/client.go
xoa/internal/mocks.go
xoa/provider_test.go

Summary: Ensure all invocations of XO client creation provide retry parameters
This is an extension of #262 and gets things one step closer to having master builds for #264 working. In the previous PR, I missed that there were a few additional invocations of XO client creation that were missing the new retry parameters. This caused the build to have a single flaky test since that client was used exclusively for it.
Testing done: Verified that Jenkins build became stable after this change

Ensure all invocations of XO client creation provide retry parameters

---

Makefile
client/client.go
xoa/acc_setup_test.go
xoa/resource_xenorchestra_vm_test.go

Summary: Run sweeper unconditionally on acc test runs and add CI Makefile target
This change is the final step needed to get master builds stable for #264. Future work will be done to surface these build statuses, but for now having CI running nightly is a great first step. The other change bundled with opting the `TestAccXenorchestraVm_addVifAndRemoveVif` test into waiting for the VM's network interface to have an IP, which sped up the given test case.
Testing done: Jenkins build has been stable with these changes

Run sweeper unconditionally on acc test runs and add CI Makefile target

---

.gitattributes
.gitignore
Makefile

Summary: Remove git lfs from the repo to avoid quota exhausted issues in CI build
One of the provider acceptance tests requires an ISO file needed to test the `xenorchestra_vdi` resource. This was originally accomplished by putting the ISO file in git lfs. Now that Jenkins is running nightly builds, I noticed that GitHub has a special quota for these files and this repo has exhausted it's free limit. 
```
> git checkout -f 9d5e64787ea2f2e36f0c4753f708ceb61a409017 # timeout=10
FATAL: Could not checkout 9d5e64787ea2f2e36f0c4753f708ceb61a409017
hudson.plugins.git.GitException: Command "git checkout -f 9d5e64787ea2f2e36f0c4753f708ceb61a409017" returned status code 128:
stdout: 
stderr: Downloading xoa/testdata/alpine-virt-3.17.0-x86_64.iso (51 MB)
Error downloading object: …
```

Remove git lfs from the repo to avoid quota exhausted issues in CI build

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml

Summary: Upgrade the broken goreleaser GitHub action and all the other actions in use
The v0.25.1 [release failed](https://github.com/terra-farm/terraform-provider-xenorchestra/actions/runs/6465539070) to build due to the following error:
```
Annotations
1 warning
[goreleaser](https://github.com/terra-farm/terraform-provider-xenorchestra/actions/runs/6465539070/job/17551892888)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-go@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
This change upgrades goreleaser and all of the other GitHub actions to recent versions.
Testing done: Triggering the GitHub actions CI job and …

Upgrade the broken goreleaser GitHub action and all the other actions in use

---

Jenkinsfile
Makefile
client/client.go

Summary: Pre download terraform cli to Jenkins and use `TF_ACC_TERRAFORM_PATH` to prevent disk space issues
The terraform-plugin-sdk has the ability to automatically download a given terraform version when running acceptance tests. This seemed extremely flexible from the beginning, but it causes `/tmp` to fill up with multiple copies of the same cli (a given version is installed on each test run).
This also opens up the ability to add opentofu builds and will be completed in an upcoming PR.
Test plan: Build should succeed and not run Jenkins out of disk space

Pre download terraform cli to Jenkins and use `TF_ACC_TERRAFORM_PATH` to prevent disk space issues

---

client/vm.go
xoa/resource_xenorchestra_vm_test.go

Summary: Separate VM creation into create and start when possible
This is follow up to the conversation mentioned here (https://github.com/terra-farm/terraform-provider-xenorchestra/issues/263#issuecomment-1776649624). The goal is to merge this ahead of #263 and then update that branch to be compatible with it (I believe it will require some minor tweaks).
Testing Done: Jenkins job is passing

Separate VM creation into create and start when possible

---

client/client.go
client/vm.go
xoa/internal/state/migrate.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Summary: Allow VM resource's `power_state` to be managed
The VM resource's previous `power_state` attribute was computed and didn't allow for specifying the state as an input. This change implements the necessary support for creating VMs with a non default `power_state` and to manage the lifecycle of it as needed.
Testing Done: The following checks were successful
Todo:

Allow VM resource's `power_state` to be managed

---

go.mod
go.sum
xoa/provider_test.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Summary: Address crashes caused by lazily bound mac address values
This fixes #191 and #232 and closes #236. This PR modifies how mac address values are handled at diff evaluation time rather than enforcing a specific format within terraform's state. Rather than using `StateFunc`, which has issues with computed fields, this suppresses a plan's diff if the pre and post plan mac address are equal to each other using [Go's HardwareAddr type](https://pkg.go.dev/net#ParseMAC). 
Test plan:

Address crashes caused by lazily bound mac address values

---

Jenkinsfile
client/vm.go
docs/data-sources/vms.md
docs/resources/vm.md
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Summary: Add full clone vm support
This closes #259 and allows VM's to have it's clone type specified.
Test plan: New tests validate the expected behavior

Add full clone vm support

---

Jenkinsfile

Summary: Upgrade latest terraform in CI job to latest version (v1.7.0)
This PR updates the latest terraform version in the jenkins job to v1.7.0 since it was released today.
Test plan: Jenkins job should pass on v1.7.0

Upgrade latest terraform in CI job to latest version (v1.7.0)

---

Makefile
client/setup_test.go

Summary: Prevent local acc test runs from clashing with Jenkins builds
This addresses #290.
Test plan:

Prevent local acc test runs from clashing with Jenkins builds

---

xoa/resource_xenorchestra_vm.go

This PR makes the provider behave the same as the XO UI.
The UI will set repository to `pxe` when `network` method is selected.
The `repository` field is mandatory, and must have length > 0 (all strings do) as seen [in the XO code](https://github.com/vatesfr/xen-orchestra/blob/6056a618c3e503fcc0de4fe19007574e40bfddd5/packages/xo-server/src/xo-mixins/rest-api.mjs#L309)
fixes #311

Set 'repository' in Installation when method is 'network'

---

client/client.go
client/vm.go
xoa/resource_xenorchestra_vm_test.go

This unblocks the remaining work to merge #305.

Use previous terraform releases for V0 to V1 state migration test

---

client/vm.go
docs/data-sources/vms.md
docs/resources/vm.md
examples/resources/xenorchestra_vm/resource.tf
xoa/data_source_vms.go
xoa/internal/state/migrate.go
xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Summary: Replace VM resource's `wait_for_ip` functionality to validate it whether the ip(s) match a given prefix
This PR is a work in progress change for addressing #300.
Testing done:

Replace VM resource's `wait_for_ip` functionality to validate it whether the ip(s) match a given prefix

---

xoa/resource_xenorchestra_vm.go
xoa/resource_xenorchestra_vm_test.go

Will fix #338 
When destroy_cloud_config_vdi_after_boot is set to true, it requires the set the power_state to "Running" even if the power_state changes are ignored in resource lifecycle (for example when the cm is stopped).
With this PR, when destroy_cloud_config_vdi_after_boot=true it will check if power_state is "Running" only if it has changed

fix issue when ignoring destroy_cloud_config_vdi_after_boot

---

docs/resources/vm.md
xoa/resource_xenorchestra_vm.go

by focusing more on the fact that the provider will wait for the
addresses to appear and mentioning the former wait_for_ip

doc: clarify expected_ip_cidr and ipv4_addresses/ipv6_addresses doc

---

go.mod
go.sum
xoa/resource_xenorchestra_bonded_network.go
xoa/resource_xenorchestra_network.go

This is related to issue https://github.com/vatesfr/terraform-provider-xenorchestra/issues/347 on terraform-provider-xenorchestra and come with https://github.com/vatesfr/xenorchestra-go-sdk/pull/18
The problem was that the param default_is_locked was always sent with the update, that make the request failed when the VIF is used.

fix: bug with network update that failed with the error "vif in use"
