.travis.yml, Makefile
=> Get travis build working

client/pif.go, client/pif_test.go, client/vm.go, xoa/data_source_xenorchestra_pif.go, xoa/data_source_xenorchestra_pif_test.go, xoa/resource_xenorchestra_vm_test.go
=> Make VLAN a required parameter for the PIF data source

client/client.go, client/pif.go, client/template.go
=> Refactor getAllObject rpc calls into generic method

README.md
Just some information to keep newbies from trying to compile the provider, when all they need to do ist to download the per-compiled binary.
=> Add some newbie instructions.

client/vm.go, go.mod, go.sum, modules/reference/pages/resource_vm.adoc, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
Reverts terra-farm/terraform-provider-xenorchestra#41
=> Revert "Implement simple runtime updates for the xo_vm resource"

.travis.yml, Makefile
=> Upgrade to go 1.15

client/client.go, client/vif.go, client/vif_test.go, client/vm.go, xoa/internal/testing.go, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
This was already merged in #51 but was accidentally reverted so I'm re-merging it
=> Store vm resource network config in tf state

client/vm.go, docs/resources/vm.md, xoa/internal/testing.go, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
This is the same code change as #64.
=> Add mac address support fully tested

README.md, docs/index.md
Hopefully this will encourage people to move to terraform 0.13.
=> Move terraform 0.13 instructions before 0.12 and lower

client/vm.go, client/vm_test.go, docs/resources/vm.md, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
=> Add resource set support for the vm resource

docs/data-sources/network.md, docs/data-sources/pif.md, docs/data-sources/pool.md, docs/data-sources/sr.md, docs/data-sources/template.md, docs/index.md, docs/resources/cloud_config.md, docs/resources/vm.md
This fixes syntax errors in the documentation from #70 .
=> Pull in updates from #70

CONTRIBUTING.md, Makefile, go.mod
This PR adds a contributor doc to explain the process on how to run the test suite. It also improves the Makefile to make it easier to run the test suite.
=> Add docs for contributors and improve the Makefile to make running tests easier

docs/index.md
This issue was identified in #92
=> Fix installation instructions for terraform 0.13 and newer

client/vdi.go, client/vm.go, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
=> Add name description attribute to disks and implement name_label and name_description attribute updates

docs/resources/cloud_config.md, docs/resources/vm.md
=> Fix cloud init comment string in vm and cloud_config resource docs

CONTRIBUTING.md, client/client.go, client/vdi.go, client/vdi_test.go, docs/data-sources/vdi.md, xoa/acc_setup_test.go, xoa/data_source_xenorchestra_sr.go, xoa/data_source_xenorchestra_vdi.go, xoa/data_source_xenorchestra_vdi_test.go, xoa/provider.go, xoa/provider_test.go
This is the first part of supporting creating VM's from diskless templates and installing from an ISO (#108)
=> Add vdi data source

CONTRIBUTING.md, client/setup_test.go, client/template.go, client/template_test.go, client/vdi.go, client/vm.go, docs/resources/vm.md, xoa/acc_setup_test.go, xoa/provider_test.go, xoa/resource_xenorchestra_vm.go, xoa/resource_xenorchestra_vm_test.go
=> Add support for creating VMs with diskless templates from an ISO

xoa/data_source_cloud_config.go, xoa/data_source_cloud_config_test.go, xoa/data_source_host.go, xoa/data_source_host_test.go, xoa/data_source_pool.go, xoa/data_source_pool_test.go, xoa/data_source_resource_set.go, xoa/data_source_resource_set_test.go, xoa/data_source_user.go, xoa/data_source_user_test.go, xoa/data_source_xenorchestra_network_test.go, xoa/data_source_xenorchestra_pif.go, xoa/data_source_xenorchestra_pif_test.go, xoa/data_source_xenorchestra_sr.go, xoa/data_source_xenorchestra_sr_test.go, xoa/data_source_xenorchestra_template.go, xoa/data_source_xenorchestra_template_test.go, xoa/data_source_xenorchestra_vdi.go, xoa/data_source_xenorchestra_vdi_test.go
=> Update all data sources to error when no results are returned

docs/resources/vm.md
This was documentation that should have been added in #144
=> Add more context on how VM updates can be performed online to avoid stop/start'ing the VM

Makefile, xoa/resource_xenorchestra_vm_test.go
=> Parallelize vm resource tests

docs/data-sources/hosts.md
Update documentation to have a working example along with make it a bit more descriptive.
issue #185
=> Correct documentation for affinity_host example.

docs/resources/vm.md
=> Include a templated cloudinit example in the xenorchestra_vm resource's docs

xoa/resource_xenorchestra_vm_test.go
TSIA
Test plan: Verify that the jenkins build passes
=> Modernize the tf variable syntax for acceptance test files

go.mod, go.sum, xoa/provider_test.go, xoa/resource_xenorchestra_vm_test.go
This test coverage will need to be reconsidered. See https://github.com/vatesfr/terraform-provider-xenorchestra/issues/298#issuecomment-1968692560 and https://github.com/vatesfr/terraform-provider-xenorchestra/issues/303
=> Remove usage of macaddress from repository

docs/resources/vm.md, examples/resources/xenorchestra_vm/resource.tf
=> update xenorchestra_vm example, valid hcl

docs/data-sources/pif.md, docs/resources/bonded_network.md, go.mod, go.sum, xoa/data_source_xenorchestra_pif.go, xoa/resource_xenorchestra_bonded_network.go
Fix #346 
I also added to the pif data_source, fields related to bond.
=> fix: imported xenorchestra_bonded_network is missing some fields #346
